### ISSUE TITLE
 Cant Find tag_c

### ISSUE THREAD

**Issue by ll01** [ebassi/taglib-rust#4]
When I try to compile the program the compiler says cannot open/find tag_c

**Comment by pulse0ne** [comment]
@ll01 Do you have the taglib-devel package installed? Not sure how to do this on windows, but on linux it should be in the repos of your distribution

**Comment by cdown** [comment]
You need [TagLib](http://taglib.org/) installed on your system to build. This can be found in the following packages:

- Arch Linux: [taglib](https://www.archlinux.org/packages/extra/x86_64/taglib/)
- CentOS/Fedora: taglib
- Gentoo: [media-libs/taglib](https://packages.gentoo.org/packages/media-libs/taglib)
- Ubuntu/Debian: [libtagc0-dev](https://packages.debian.org/search?searchon=names&keywords=libtagc0-dev)

**Comment by Losses** [comment]
@cdown Hmmmm what about Windows? it seems `taglib` is not in vcpkg?

**Comment by cdown** [comment]
I have no idea about Windows, sorry.
