### ISSUE TITLE
Version on crates.io does not work, please update

### ISSUE THREAD

**Issue by izderadicka** [ebassi/taglib-rust#5]
On crates.io is version 0.2 from 2016, which does not have latest fixes - especially the CString pointer fixes - so it does not work in beta at all - it would be nice if it can be updated also there.

**Comment by pulse0ne** [comment]
Bump. The version on crates.io is broken.

**Comment by cdown** [comment]
A new release would be great, right now one has to use github directly in Cargo.toml, which is non-ideal.

**Comment by cdown** [comment]
Looking at the state of current PRs, looks like @ebassi isn't actively maintaining this any more. I've sent him an e-mail to ask if I can take over ownership of the package.

**Comment by cdown** [comment]
Good news! @ebassi was kind enough to add commit access to this repository, so I'll try to fix things up and get a new version on crates.io soon. :-)

**Comment by cdown** [comment]
1.0.0 is released on crates.io :-)
